version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

default: &default
  working_directory: ~/ndata-frontend
  docker:
    - image: circleci/node:8

jobs:
  test:
    <<: *default
    steps:
      - checkout
      - run: yarn install
      - run: yarn test --updateSnapshot --collectCoverage
      - store_test_results:
          path: coverage/lcov.info
      - store_artifacts: # upload test coverage as artifact
          path: coverage

  build:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy-uat:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - aws-s3/sync:
          from: build
          to: '$UAT_BUCKET'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2

  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test

  build-deploy-uat:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: develop
          context: uat
      - deploy-uat:
          requires:
            - build
          filters:
            branches:
              only: develop
          context: uat
