version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20

default: &default
  working_directory: /home/circleci/ndata-frontend
  docker:
    - image: circleci/node:8

jobs:
  test:
    <<: *default
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test --updateSnapshot --runInBand --reporters=default --reporters=jest-junit --collectCoverage=true
          environment:
            JEST_JUNIT_OUTPUT_DIR: './test-results/junit/results.xml'
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./coverage

  build:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: CI=false GENERATE_SOURCEMAP=false yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: /home/circleci/ndata-frontend
          paths: build/

  deploy:
    <<: *default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/ndata-frontend
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: Sync assets 
          command: aws s3 sync build s3://$S3StaticBucket/ --delete
      - run:
          name: CDN invalidations 
          command: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2
  # build_and_test:
  #   jobs:
  #     - test
  #     - build:
  #         requires:
  #           - test
  build-deploy-uat:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: fer/develop
          context: ndata_dev
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: fer/develop
          context: ndata_dev
