// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id:
    'us-west-2:6521a659-6d86-41b2-8809-faa26999a3f5',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_iWgX8lonM',
  aws_user_pools_web_client_id: '1qo43u5q6gf9efcqmt20mbf5ph',
  oauth: {},
  aws_content_delivery_bucket:
    'ndata-frontend-20191020024314-hostingbucket-dev',
  aws_content_delivery_bucket_region: 'us-west-2',
  aws_content_delivery_url: 'https://d2c51q64zs1nzp.cloudfront.net',
};

export default awsmobile;
